### ISSUE TITLE
When the storage type is set to elasticsearch, browse http://localhost:9411/ Abnormal happen:

### ISSUE THREAD

**Issue by vwyuheng** [openzipkin/zipkin-java#174]
org.elasticsearch.search.aggregations.AggregationExecutionException: [nested] nested path [binaryAnnotations] is not nested
	at org.elasticsearch.search.aggregations.bucket.nested.NestedAggregator$Factory.createInternal(NestedAggregator.java:160)
	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87)
	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:85)
	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:111)
	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:364)
	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:376)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by adriancole** [comment]
What version of elasticsearch are you using?

**Comment by vwyuheng** [comment]
2.2.1

**Comment by adriancole** [comment]
I just fired up zipkin against elasticsearch locally, and was unable to reproduce the problem, just by hitting localhost.

@anuraaga any ideas?

**Comment by vwyuheng** [comment]
zipkin-java version 0.14.0   es version 2.2.1,  zipkin-server config as follows：
elasticsearch:
  cluster: mytrace
  hosts: 10.58.56.132:9300,10.58.56.133:9300,10.58.56.134:9300
  index: trace
kafka:
  # ZooKeeper host string, comma-separated host:port value.
  zookeeper: 10.58.56.134:2181,10.58.56.134:2182,10.58.56.134:2183
  # Name of topic to poll for spans
  topic: trace
  # Consumer group this process is consuming on behalf of.
  group-id: trace
  # Count of consumer threads consuming the topic
  streams: 5
eagleye:
  self-tracing:
    # Set to false to disable self-tracing. Defaults to true
    enabled: false
    # Interval in seconds to flush self-tracing data to storage.
    flush-interval: 1
  collector:
    # percentage to traces to retain
    sample-rate: 1.0
  query:
    # 7 days in millis
    lookback: 86400000
  storage:
    type: elasticsearch
  ui:
    ## Values below here are mapped to ZipkinServerProperties.UI, served as /config.json
    # Default limit for Find Traces
    query-limit: 100
    # The value here becomes a label in the top-right corner
    environment: test
    # Default duration to look back when finding traces or dependency links.
    # Affects the "Start time" element in the UI. 7 days in millis
    default-lookback: 604800000
server:
  port: 9411
  compression:
    enabled: true
    # compresses any response over min-response-size (default is 2KiB)
    # Includes dynamic json content and large static assets from zipkin-ui
    mime-types: application/json,application/javascript,text/css,image/svg
spring:
  mvc:
    favicon:
      # zipkin has its own favicon
      enabled: false
  autoconfigure:
    exclude:
      # otherwise we might initialize even when not needed (ex when storage type is cassandra)
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    # Silence Invalid method name: '__can__finagle__trace__v3__'
    com.facebook.swift.service.ThriftServiceProcessor: 'OFF'
#     # investigate /api/v1/dependencies
#     zipkin.internal.DependencyLinker: 'DEBUG'
#     # log cassandra calls
#     org.twitter.zipkin.storage.cassandra.Repository: 'DEBUG'
please help me，thanks

**Comment by adriancole** [comment]
did you figure it out?

**Comment by vwyuheng** [comment]
When I was   update，after this problem haven't appeared

**Comment by vwyuheng** [comment]
so I think it should be before the version is not compatible
