### ISSUE TITLE
NPE coming from CassandraSpanStore

### ISSUE THREAD

**Issue by mikewrighton** [openzipkin/zipkin-java#199]
I'm seeing the following NPE when I try to query by duration:

```
java.lang.NullPointerException: null
	at com.google.common.collect.Iterables$3.transform(Iterables.java:512) ~[guava-18.0.jar:na]
	at com.google.common.collect.Iterables$3.transform(Iterables.java:509) ~[guava-18.0.jar:na]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[guava-18.0.jar:na]
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548) ~[guava-18.0.jar:na]
	at zipkin.cassandra.CassandraSpanStore$11.apply(CassandraSpanStore.java:575) ~[zipkin-storage-cassandra-0.17.0.jar:na]
	at zipkin.cassandra.CassandraSpanStore$11.apply(CassandraSpanStore.java:571) ~[zipkin-storage-cassandra-0.17.0.jar:na]
	at com.google.common.util.concurrent.Futures$2.apply(Futures.java:760) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$CombinedFuture.setOneValue(Futures.java:1764) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$CombinedFuture.access$400(Futures.java:1608) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$CombinedFuture$2.run(Futures.java:1686) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:202) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:940) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145) ~[guava-18.0.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185) ~[guava-18.0.jar:na]
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:174) ~[cassandra-driver-core-3.0.1.jar:na]
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177) ~[cassandra-driver-core-3.0.1.jar:na]
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43) ~[cassandra-driver-core-3.0.1.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:792) ~[cassandra-driver-core-3.0.1.jar:na]
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:467) ~[cassandra-driver-core-3.0.1.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1013) ~[cassandra-driver-core-3.0.1.jar:na]
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:936) ~[cassandra-driver-core-3.0.1.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) ~[netty-handler-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) ~[netty-codec-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.33.Final.jar:4.0.33.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]
```

**Comment by adriancole** [comment]
oh interesting! one of the futures must have failed. Will fix.
