### ISSUE TITLE
InvalidQueryException: Partition KEY part service_name cannot be restricted by IN relation

### ISSUE THREAD

**Issue by gena01** [openzipkin/zipkin-java#208]
Just loaded up the zipkin UI for docker image with current 0.18 tag and got a bunch of exceptions in the log and in the network tab in Firefox:

I am seeing this in Docker logs:
com.datastax.driver.core.exceptions.InvalidQueryException: Partition KEY part service_name cannot be restricted by IN relation (only the last part of the partition key can)

2016-05-06 18:59:51.812 ERROR 5 --- [nio-9411-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spanStore' defined in class path resource [zipkin/server/ZipkinServerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [zipkin.SpanStore]: Factory method 'spanStore' threw exception; nested exception is java.lang.reflect.UndeclaredThrowableException] with root cause

and a bunch of these:
2016-05-06 18:59:51.807 WARN 5 --- [uster2-worker-5] com.datastax.driver.core.Cluster : Re-preparing already prepared query SELECT span_name FROM span_names WHERE service_name=:service_name AND bucket=:bucket LIMIT :limit_;. Please note that preparing the same query more than once is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once.
2016-05-06 18:59:51.802 WARN 5 --- [uster2-worker-4] com.datastax.driver.core.Cluster : Re-preparing already prepared query SELECT service_name FROM service_names;. Please note that preparing the same query more than once is generally an anti-pattern and will likely affect performance. Consider preparing the statement only once.

**Comment by adriancole** [comment]
The warnings aren't new, but the error is surprising.

I just ran `docker-compose -f docker-compose-cassandra.yml up` and hit the
api without getting that error.  Are you using a custom image? or a
different version of cassandra perhaps?

**Comment by adriancole** [comment]
Quick googling on that error.. I'm guessing you have a custom schema? The
error seems possible if using "compact storage"

We use "'class':
'org.apache.cassandra.db.compaction.DateTieredCompactionStrategy"

https://github.com/openzipkin/zipkin-java/blob/master/zipkin-storage/cassandra/src/main/resources/cassandra-schema-cql3.txt#L9

**Comment by adriancole** [comment]
This is because cassandra 2.1 is being used, and a recent query update wasn't supported. We don't test on cassandra 2.1, and haven't since [last september](https://github.com/openzipkin/docker-zipkin/commit/19a70058e7823c64e8094386c1db354796ecb283#diff-54fd4195197d450627e22c65180cb751)

While the [README](https://github.com/openzipkin/zipkin-java/tree/master/zipkin-storage/cassandra#storage-cassandra) mentions that cassandra 2.2 is the minimum version, we can make that more explicit in the docker repo. I'll do an update there.

---
Here's how I tested.

```bash
# in one tab, start cassandra 2.1
$ export CASSANDRA_HOME=$HOME/Downloads/dsc-cassandra-2.1.14/
$CASSANDRA_HOME/bin/cassandra -f

# in another, start a zipkin server
$ STORAGE_TYPE=cassandra java -jar zipkin-server/target/zipkin-server-0.18.1-SNAPSHOT-exec.jar

# in another, try and fail a query
$ curl -s localhost:9411/api/v1/traces
{"timestamp":1462584323799,"status":500,"error":"Internal Server Error","exception":"org.springframework.beans.factory.BeanCreationException","message":"Error creating bean with name 'spanStore' defined in class path resource [zipkin/server/ZipkinServerConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [zipkin.SpanStore]: Factory method 'spanStore' threw exception; nested exception is java.lang.reflect.UndeclaredThrowableException","path":"/api/v1/traces"}✔ ~

# look at the server-window and see the error about the query
com.datastax.driver.core.exceptions.InvalidQueryException: Partition KEY part service_name cannot be restricted by IN relation (only the last part of the partition key can)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:136) ~[cassandra-driver-core-3.0.1.jar!/:na]
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220) ~[cassandra-driver-core-3.0.1.jar!/:na]
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196) ~[cassandra-driver-core-3.0.1.jar!/:na]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906) ~[guava-18.0.jar!/:na]
	at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635) ~[guava-18.0.jar!/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_73]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]
```

**Comment by adriancole** [comment]
posted some PSAs

https://twitter.com/zipkinproject/status/728765469969108992
https://groups.google.com/forum/#!topic/zipkin-user/s6NZctGdNJM

**Comment by adriancole** [comment]
opened https://github.com/openzipkin/zipkin-java/pull/210 to buy you some more time
